version: "3.9"
services:
  afd:
    build: .
    container_name: afd-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:rw
    environment:
      - TZ=America/Guatemala
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
